{% set name = "meteofetch" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/meteofetch-{{ version }}.tar.gz
  sha256: 0d225e63cbb58f61518116696ffe3c19e31a9da3224befddda666a6c5a863909

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - cfgrib
    - requests
    - xarray

test:
  imports:
    - meteofetch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Package python pour recuperer les donnees modelisees de prevision de MeteoFrance
  home: https://github.com/CyrilJl/MeteoFetch
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CyrilJl
